name: ci
on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  debug:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  release:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --release --verbose

  rustfmt:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add rustfmt
    - name: Run rustfmt
      run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - run: rustup component add clippy
    - uses: actions-rs/clippy-check@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        args: --all-features
